services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  medusa-backend:
    build:
      context: ./my-medusa-store
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: docker
      DATABASE_URL: postgres://medusa:medusa@postgres:5432/medusa?sslmode=disable
      ADMIN_CORS: http://localhost:9000
      STORE_CORS: http://localhost:8000,http://localhost:3000,http://medusa-storefront:8000
      AUTH_CORS: http://localhost:9000
      JWT_SECRET: supersecret
      COOKIE_SECRET: supersecret
      MEDUSA_BACKEND_URL: http://medusa-backend:9000
      REDIS_URL: redis://redis:6379
      REDIS_URI: redis://redis:6379
    ports:
      - "9000:9000"
    working_dir: /app


  medusa-storefront:
    build:
      context: ./my-medusa-store-storefront
      dockerfile: Dockerfile
    depends_on:
      - medusa-backend
    environment:
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://localhost:9000
      NEXT_PUBLIC_BASE_URL: http://localhost:8000
      MEDUSA_BACKEND_URL: http://medusa-backend:9000
      NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY: pk_test_key
      NEXT_PUBLIC_DEFAULT_REGION: us
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./my-medusa-store-storefront:/app
      - /app/node_modules
      - /app/.next


volumes:
  pgdata: